error: uncaughtException: Access denied for user 'Mayur'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 12:47:22 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1205669.14},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":42665,"external":3085721,"heapTotal":98205696,"heapUsed":44706464,"rss":136163328},"pid":28816,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Access denied for user 'Mayur'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 12:48:16 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1205722.437},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":26281,"external":3069337,"heapTotal":92561408,"heapUsed":42871944,"rss":128249856},"pid":43900,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Access denied for user 'Mayur'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 12:50:53 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1205880.25},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":354999,"external":3401486,"heapTotal":88702976,"heapUsed":62518552,"rss":126898176},"pid":16616,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Access denied for user 'Mayur'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 12:50:57 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1205884.156},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":26281,"external":3069337,"heapTotal":91774976,"heapUsed":42588512,"rss":128151552},"pid":31920,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Access denied for user 'Mayur'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 13:11:22 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1207109.328},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":34473,"external":3077529,"heapTotal":90988544,"heapUsed":42401664,"rss":126349312},"pid":40476,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Access denied for user 'Mayur'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 13:12:23 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1207170.218},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":26281,"external":3069337,"heapTotal":90202112,"heapUsed":41744704,"rss":126345216},"pid":15780,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Access denied for user 'Mayur'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 13:14:24 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1207291.156},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":26281,"external":3069337,"heapTotal":91512832,"heapUsed":42610136,"rss":128688128},"pid":41508,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Please install tedious package manually
Error: Please install tedious package manually
    at ConnectionManager._loadDialectModule (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:81:15)
    at new ConnectionManager (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:16:21)
    at new MssqlDialect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\index.js:15:30)
    at new Sequelize (D:\CPAI_Node\demo_project\node_modules\sequelize\src\sequelize.js:368:20)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\config\/database.js:25:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\services\/user.service.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\controllers\/user.controller.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\routes\/user.route.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\routes\/index.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\/index.js:8:1) {"date":"Wed May 08 2024 14:39:38 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1212405.234},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":48381,"external":2982440,"heapTotal":82337792,"heapUsed":58074576,"rss":118792192},"pid":34496,"uid":null,"version":"v20.10.0"},"stack":"Error: Please install tedious package manually\n    at ConnectionManager._loadDialectModule (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:81:15)\n    at new ConnectionManager (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:16:21)\n    at new MssqlDialect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\index.js:15:30)\n    at new Sequelize (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\sequelize.js:368:20)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\config\\/database.js:25:19)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\services\\/user.service.js:1:1)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\controllers\\/user.controller.js:2:1)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\routes\\/user.route.js:2:1)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\routes\\/index.js:4:1)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\/index.js:8:1)","trace":[{"column":15,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._loadDialectModule","line":81,"method":"_loadDialectModule","native":false},{"column":21,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"new ConnectionManager","line":16,"method":null,"native":false},{"column":30,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\index.js","function":"new MssqlDialect","line":15,"method":null,"native":false},{"column":20,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\sequelize.js","function":"new Sequelize","line":368,"method":null,"native":false},{"column":19,"file":"D:\\CPAI_Node\\demo_project\\src\\config\\/database.js","function":null,"line":25,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\services\\/user.service.js","function":null,"line":1,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\controllers\\/user.controller.js","function":null,"line":2,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\routes\\/user.route.js","function":null,"line":2,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\routes\\/index.js","function":null,"line":4,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\/index.js","function":null,"line":8,"method":null,"native":false}]}
error: uncaughtException: Please install tedious package manually
Error: Please install tedious package manually
    at ConnectionManager._loadDialectModule (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:81:15)
    at new ConnectionManager (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:16:21)
    at new MssqlDialect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\index.js:15:30)
    at new Sequelize (D:\CPAI_Node\demo_project\node_modules\sequelize\src\sequelize.js:368:20)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\config\/database.js:25:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\services\/user.service.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\controllers\/user.controller.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\routes\/user.route.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\routes\/index.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\/index.js:8:1) {"date":"Wed May 08 2024 14:43:16 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1212623.109},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":48381,"external":2982440,"heapTotal":82075648,"heapUsed":58286336,"rss":118951936},"pid":39576,"uid":null,"version":"v20.10.0"},"stack":"Error: Please install tedious package manually\n    at ConnectionManager._loadDialectModule (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:81:15)\n    at new ConnectionManager (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:16:21)\n    at new MssqlDialect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\index.js:15:30)\n    at new Sequelize (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\sequelize.js:368:20)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\config\\/database.js:25:19)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\services\\/user.service.js:1:1)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\controllers\\/user.controller.js:2:1)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\routes\\/user.route.js:2:1)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\routes\\/index.js:4:1)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\/index.js:8:1)","trace":[{"column":15,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._loadDialectModule","line":81,"method":"_loadDialectModule","native":false},{"column":21,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"new ConnectionManager","line":16,"method":null,"native":false},{"column":30,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\index.js","function":"new MssqlDialect","line":15,"method":null,"native":false},{"column":20,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\sequelize.js","function":"new Sequelize","line":368,"method":null,"native":false},{"column":19,"file":"D:\\CPAI_Node\\demo_project\\src\\config\\/database.js","function":null,"line":25,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\services\\/user.service.js","function":null,"line":1,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\controllers\\/user.controller.js","function":null,"line":2,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\routes\\/user.route.js","function":null,"line":2,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\routes\\/index.js","function":null,"line":4,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\/index.js","function":null,"line":8,"method":null,"native":false}]}
error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 14:44:44 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1212710.89},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":25283,"external":3102133,"heapTotal":99979264,"heapUsed":49196760,"rss":134905856},"pid":29500,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Failed to connect to Mayur\LOCALDB#BDCCF332:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to Mayur\LOCALDB#BDCCF332:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 14:46:53 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1212839.937},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":25283,"external":3102133,"heapTotal":96727040,"heapUsed":47689320,"rss":135180288},"pid":27360,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to Mayur\\LOCALDB#BDCCF332:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Failed to connect to localhost:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to localhost:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 14:50:05 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1213032.156},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":25283,"external":3102133,"heapTotal":98299904,"heapUsed":48480272,"rss":133771264},"pid":11044,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to localhost:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Failed to connect to localhost:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to localhost:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 15:21:35 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1214922.093},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":25283,"external":3102133,"heapTotal":98037760,"heapUsed":48903968,"rss":134553600},"pid":40432,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to localhost:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 15:26:13 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1215200},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":587373,"external":3669484,"heapTotal":95813632,"heapUsed":69380568,"rss":135208960},"pid":35184,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 15:27:56 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1215302.859},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":25283,"external":3102133,"heapTotal":94998528,"heapUsed":45798936,"rss":131276800},"pid":38692,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 15:49:46 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1216613.093},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":571899,"external":3654010,"heapTotal":96075776,"heapUsed":72321352,"rss":135782400},"pid":23644,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 15:51:50 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1216737.062},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":570945,"external":3653056,"heapTotal":96600064,"heapUsed":72528328,"rss":135614464},"pid":21604,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 15:52:01 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1216748.078},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":25283,"external":3102133,"heapTotal":99192832,"heapUsed":48905640,"rss":134488064},"pid":29776,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Login failed for user 'sa'.
SequelizeAccessDeniedError: Login failed for user 'sa'.
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:144:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 15:55:15 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1216942.093},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":28190,"external":3105040,"heapTotal":94736384,"heapUsed":46507664,"rss":132837376},"pid":17452,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":144,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 15:55:54 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1216980.734},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":25283,"external":3102133,"heapTotal":95260672,"heapUsed":45587072,"rss":131088384},"pid":41656,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:16:02 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1218189.343},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":25283,"external":3102133,"heapTotal":94474240,"heapUsed":45575904,"rss":130498560},"pid":23080,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Connection lost - Unable to process incoming packet
SequelizeConnectionError: Connection lost - Unable to process incoming packet
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:21:33 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1218519.656},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":31553,"external":3108403,"heapTotal":94998528,"heapUsed":46427616,"rss":131547136},"pid":40732,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Connection lost - Unable to process incoming packet\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Unknown database 'express'
SequelizeConnectionError: Unknown database 'express'
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mysql\connection-manager.js:126:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:21:46 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'express'","sqlState":"42000"},"parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'express'","sqlState":"42000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1218532.953},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":26254,"external":3072741,"heapTotal":83648512,"heapUsed":62549392,"rss":122699776},"pid":38124,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Unknown database 'express'\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:126:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":126,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
info: ::1 - - [08/May/2024:10:52:50 +0000] "GET /api/v1/ HTTP/1.1" 200 9 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

info: ::1 - - [08/May/2024:10:52:50 +0000] "GET /favicon.ico HTTP/1.1" 404 47 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:33:01 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1219207.421},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":25283,"external":3102133,"heapTotal":94736384,"heapUsed":45595808,"rss":130560000},"pid":35928,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:39:07 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1219573.531},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":25283,"external":3102133,"heapTotal":95784960,"heapUsed":45755136,"rss":131489792},"pid":28556,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Login failed for user 'sa'.
SequelizeAccessDeniedError: Login failed for user 'sa'.
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:144:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:47:36 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":209.328},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":28188,"external":3105038,"heapTotal":95260672,"heapUsed":46420496,"rss":133378048},"pid":14492,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":144,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Login failed for user 'sa'.
SequelizeAccessDeniedError: Login failed for user 'sa'.
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:144:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:48:07 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":240.765},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":28188,"external":3105038,"heapTotal":94892032,"heapUsed":46487992,"rss":134176768},"pid":9824,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":144,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Failed to connect to 169.254.150.115:1433 in 15000ms
SequelizeConnectionError: Failed to connect to 169.254.150.115:1433 in 15000ms
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:148:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:49:29 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ETIMEOUT"},"parent":{"code":"ETIMEOUT"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":322.281},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":25283,"external":3102133,"heapTotal":94736384,"heapUsed":46001848,"rss":130801664},"pid":15924,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 169.254.150.115:1433 in 15000ms\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:148:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":148,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Failed to connect to 169.254.150.115:1433 in 15000ms
SequelizeConnectionError: Failed to connect to 169.254.150.115:1433 in 15000ms
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:148:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:50:45 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ETIMEOUT"},"parent":{"code":"ETIMEOUT"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":398.078},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":25283,"external":3102133,"heapTotal":47812608,"heapUsed":45824400,"rss":87265280},"pid":13628,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 169.254.150.115:1433 in 15000ms\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:148:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":148,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Login failed for user 'sa'.
SequelizeAccessDeniedError: Login failed for user 'sa'.
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:144:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:52:25 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":498.375},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":28188,"external":3105038,"heapTotal":94367744,"heapUsed":46467192,"rss":133046272},"pid":10016,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":144,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Login failed for user 'sa'.
SequelizeAccessDeniedError: Login failed for user 'sa'.
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:144:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:54:23 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":615.921},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":28184,"external":3105034,"heapTotal":94892032,"heapUsed":46526048,"rss":133754880},"pid":4720,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":144,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Login failed for user 'sa'.
SequelizeAccessDeniedError: Login failed for user 'sa'.
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:144:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Thu May 09 2024 11:20:55 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1498.203},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":28514,"external":3105364,"heapTotal":99872768,"heapUsed":49760432,"rss":135995392},"pid":15512,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":144,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
info: ::1 - - [09/May/2024:05:52:15 +0000] "GET /api/v1/ HTTP/1.1" 200 9 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

info: ::1 - - [09/May/2024:05:52:15 +0000] "GET /favicon.ico HTTP/1.1" 404 47 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

info: ::1 - - [09/May/2024:05:53:13 +0000] "GET /api/v1/users HTTP/1.1" 200 65 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

info: ::1 - - [09/May/2024:06:09:28 +0000] "POST /api/v1/users HTTP/1.1" 201 213 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:06:12:58 +0000] "GET /api/v1/users HTTP/1.1" 200 220 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:06:15:20 +0000] "GET /api/v1/users HTTP/1.1" 200 220 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:06:16:01 +0000] "POST /api/v1/users HTTP/1.1" 201 213 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:06:20:15 +0000] "POST /api/v1/users HTTP/1.1" 500 90 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:06:22:16 +0000] "POST /api/v1/users HTTP/1.1" 500 66 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:06:22:24 +0000] "POST /api/v1/users HTTP/1.1" 201 212 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:06:25:13 +0000] "POST /api/v1/users HTTP/1.1" - - "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:06:25:43 +0000] "POST /api/v1/users HTTP/1.1" 201 212 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:06:26:23 +0000] "GET /api/v1/users HTTP/1.1" 200 686 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:06:26:50 +0000] "GET /api/v1/users/1 HTTP/1.1" 400 56 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:06:41:47 +0000] "POST /api/v1/users HTTP/1.1" 500 109 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:06:42:39 +0000] "POST /api/v1/users HTTP/1.1" 500 109 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:06:51:57 +0000] "POST /api/v1/users HTTP/1.1" 500 58 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:06:52:49 +0000] "POST /api/v1/users HTTP/1.1" 201 212 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:06:52:55 +0000] "POST /api/v1/users HTTP/1.1" 201 212 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:06:53:32 +0000] "POST /api/v1/users HTTP/1.1" 500 54 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:06:58:21 +0000] "POST /api/v1/users HTTP/1.1" 500 56 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:06:59:00 +0000] "POST /api/v1/users HTTP/1.1" 500 54 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:06:59:19 +0000] "POST /api/v1/users HTTP/1.1" 500 54 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:00:15 +0000] "POST /api/v1/users HTTP/1.1" 500 54 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:01:36 +0000] "POST /api/v1/users HTTP/1.1" 201 60 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:01:57 +0000] "POST /api/v1/users HTTP/1.1" 201 60 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:01:58 +0000] "POST /api/v1/users HTTP/1.1" 201 60 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:03:37 +0000] "POST /api/v1/users HTTP/1.1" 500 58 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:03:38 +0000] "POST /api/v1/users HTTP/1.1" 500 58 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:08:15 +0000] "POST /api/v1/users HTTP/1.1" 409 58 "-" "PostmanRuntime/7.36.3"

error: uncaughtException: data is not defined
ReferenceError: data is not defined
    at _callee3$ (D:\CPAI_Node\demo_project\src\controllers\/user.controller.js:60:15)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.throw (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _throw (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {"date":"Thu May 09 2024 12:39:46 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":6229.093},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":129281,"external":3206131,"heapTotal":101146624,"heapUsed":59320664,"rss":138256384},"pid":18384,"uid":null,"version":"v20.10.0"},"stack":"ReferenceError: data is not defined\n    at _callee3$ (D:\\CPAI_Node\\demo_project\\src\\controllers\\/user.controller.js:60:15)\n    at tryCatch (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:45:16)\n    at Generator.<anonymous> (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:133:17)\n    at Generator.throw (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:74:21)\n    at asyncGeneratorStep (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _throw (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","trace":[{"column":15,"file":"D:\\CPAI_Node\\demo_project\\src\\controllers\\/user.controller.js","function":"_callee3$","line":60,"method":null,"native":false},{"column":16,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":45,"method":null,"native":false},{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":null,"line":133,"method":null,"native":false},{"column":21,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.throw","line":74,"method":"throw","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_throw","line":25,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false}]}
error: uncaughtException: data is not defined
ReferenceError: data is not defined
    at _callee3$ (D:\CPAI_Node\demo_project\src\controllers\/user.controller.js:60:15)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.throw (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _throw (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {"date":"Thu May 09 2024 12:40:26 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":6269.718},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":129281,"external":3206131,"heapTotal":101408768,"heapUsed":59315056,"rss":138547200},"pid":12412,"uid":null,"version":"v20.10.0"},"stack":"ReferenceError: data is not defined\n    at _callee3$ (D:\\CPAI_Node\\demo_project\\src\\controllers\\/user.controller.js:60:15)\n    at tryCatch (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:45:16)\n    at Generator.<anonymous> (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:133:17)\n    at Generator.throw (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:74:21)\n    at asyncGeneratorStep (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _throw (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","trace":[{"column":15,"file":"D:\\CPAI_Node\\demo_project\\src\\controllers\\/user.controller.js","function":"_callee3$","line":60,"method":null,"native":false},{"column":16,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":45,"method":null,"native":false},{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":null,"line":133,"method":null,"native":false},{"column":21,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.throw","line":74,"method":"throw","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_throw","line":25,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false}]}
info: ::1 - - [09/May/2024:07:11:05 +0000] "POST /api/v1/users HTTP/1.1" 409 58 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:11:07 +0000] "POST /api/v1/users HTTP/1.1" 409 58 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:11:10 +0000] "POST /api/v1/users HTTP/1.1" 409 58 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:11:17 +0000] "POST /api/v1/users HTTP/1.1" 409 58 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:11:38 +0000] "POST /api/v1/users HTTP/1.1" 409 58 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:12:35 +0000] "POST /api/v1/users HTTP/1.1" 409 58 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:13:07 +0000] "POST /api/v1/users HTTP/1.1" 500 54 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:13:17 +0000] "POST /api/v1/users HTTP/1.1" 201 210 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:13:51 +0000] "POST /api/v1/users HTTP/1.1" 409 58 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:13:58 +0000] "POST /api/v1/users HTTP/1.1" 409 58 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:19:01 +0000] "POST /api/v1/users HTTP/1.1" 201 217 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:19:06 +0000] "POST /api/v1/users HTTP/1.1" 201 217 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:19:11 +0000] "POST /api/v1/users HTTP/1.1" 201 218 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:19:38 +0000] "POST /api/v1/users HTTP/1.1" 201 213 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:19:42 +0000] "POST /api/v1/users HTTP/1.1" 201 213 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:19:55 +0000] "POST /api/v1/users HTTP/1.1" 409 58 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:19:57 +0000] "POST /api/v1/users HTTP/1.1" 409 58 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:20:04 +0000] "POST /api/v1/users HTTP/1.1" 409 58 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:20:06 +0000] "POST /api/v1/users HTTP/1.1" 409 58 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:25:08 +0000] "POST /api/v1/users HTTP/1.1" 500 54 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:28:57 +0000] "POST /api/v1/users HTTP/1.1" 500 96 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:29:05 +0000] "POST /api/v1/users HTTP/1.1" 500 96 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:30:17 +0000] "POST /api/v1/users HTTP/1.1" 500 96 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:30:34 +0000] "POST /api/v1/users HTTP/1.1" 201 218 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:30:38 +0000] "POST /api/v1/users HTTP/1.1" 500 54 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:30:41 +0000] "POST /api/v1/users HTTP/1.1" 500 54 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:31:26 +0000] "POST /api/v1/users HTTP/1.1" 409 58 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:31:27 +0000] "POST /api/v1/users HTTP/1.1" 409 58 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:31:32 +0000] "POST /api/v1/users HTTP/1.1" 201 222 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:31:33 +0000] "POST /api/v1/users HTTP/1.1" 409 58 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:48:54 +0000] "GET /api/v1/users/1 HTTP/1.1" 500 54 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:49:14 +0000] "GET /api/v1/users/1 HTTP/1.1" 200 213 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:49:19 +0000] "GET /api/v1/users/50 HTTP/1.1" 500 67 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:50:27 +0000] "GET /api/v1/users/50 HTTP/1.1" 500 78 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:52:36 +0000] "GET /api/v1/users/50 HTTP/1.1" 409 78 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:52:46 +0000] "GET /api/v1/users/1 HTTP/1.1" 200 213 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:52:51 +0000] "GET /api/v1/users/10 HTTP/1.1" 200 218 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:59:41 +0000] "PUT /api/v1/users/10 HTTP/1.1" 202 132 "-" "PostmanRuntime/7.36.3"

info: ::1 - - [09/May/2024:07:59:47 +0000] "PUT /api/v1/users/50 HTTP/1.1" 202 44 "-" "PostmanRuntime/7.36.3"

